package pix

import (
	"github.com/mikaellemos033/sdk-go-apis-efi/src/efipay/pix/request"
	"github.com/mikaellemos033/sdk-go-apis-efi/src/efipay/pix/response"
)

type Requester interface {
	Request(endpoint string, httpVerb string, requestParams map[string]string, body interface{}) (string, error)
	RequestWithHeaders(endpoint string, httpVerb string, requestParams map[string]string, body interface{}, headers map[string]interface{}) (string, error)
}

type Pix interface {
	CreateImmediateCharge(body *request.PixImmediate) (*response.PixImmediate, error)
	CreateCharge(txid string, body map[string]interface{}) (string, error)
	UpdateCharge(txid string) (string, error)
	DetailCharge(txid string) (string, error)
	ListCharges(inicio string, fim string) (string, error)
	PixDevolution(e2eid string, id string, body map[string]interface{}) (string, error)
	PixDetailDevolution(e2eid string, id string) (string, error)
	PixSend(idEnvio string, body map[string]interface{}) (string, error)
	PixSendList(e2eid string) (string, error)
	PixSendDetail(e2eid string) (string, error)
	PixCreateLocation(body map[string]interface{}) (string, error)
	PixUnlinkTxidLocation(id string, body map[string]interface{}) (string, error)
	PixDetailLocation(id string) (string, error)
	PixLocationList(inicio string, fim string) (string, error)
	PixGenerateQRCode(id string) (string, error)
	GetAccountBalance(body map[string]interface{}) (string, error)
	ListAccountConfig(body map[string]interface{}) (string, error)
	UpdateAccountConfig(body map[string]interface{}) (string, error)
	PixCreateEvp(body map[string]interface{}) (string, error)
	PixListEvp(body map[string]interface{}) (string, error)
	PixDeleteEvp(key string, body map[string]interface{}) (string, error)
	PixConfigWebhook(chave string, body map[string]interface{}) (string, error)
	PixConfigWebhookWithoutTLS(chave string, body map[string]interface{}) (string, error)
	PixDeleteWebhook(chave string, body map[string]interface{}) (string, error)
	PixDetailWebhook(chave string) (string, error)
	PixListWebhooks(inicio string, fim string) (string, error)
	CreateDueCharge(txid string, body map[string]interface{}) (string, error)
	PixUpdateDueCharge(txid string, body map[string]interface{}) (string, error)
	DetailDueCharge(txid string) (string, error)
	PixListDueCharges(params map[string]string) (string, error)
	CreateReport(body map[string]interface{}) (string, error)
	DetailReport(id string) (string, error)
	PixReceivedList(params map[string]string) (string, error)
	PixDetailReceived(e2eid string) (string, error)
	PixSplitDetailCharge(txid string) (string, error)
	PixSplitLinkCharge(txid string, splitConfigId string) (string, error)
	PixSplitUnlinkCharge(txid string, splitConfigId string) (string, error)
	PixSplitDetailDueCharge(txid string) (string, error)
	PixSplitLinkDueCharge(txid string, splitConfigId string) (string, error)
	PixSplitUnlinkDueCharge(txid string, splitConfigId string) (string, error)
	PixSplitConfig(body map[string]interface{}) (string, error)
	PixSplitConfigId(id string, body map[string]interface{}) (string, error)
	PixSplitDetailConfig(id string) (string, error)
	PixCreateAutomaticCharge(body map[string]interface{}) (string, error)
	PixCreateAutomaticChargeTxid(txid string, body map[string]interface{}) (string, error)
	PixDetailAutomaticCharge(txid string) (string, error)
	PixListAutomaticCharge(inicio string, fim string) (string, error)
	PixRetryRequestAutomatic(txid string, data string) (string, error)
	PixUpdateAutomaticCharge(txid string, body map[string]interface{}) (string, error)
	PixCreateRecurrenceAutomatic(body map[string]interface{}) (string, error)
	PixCreateRequestRecurrenceAutomatic(body map[string]interface{}) (string, error)
	PixCreateLocationRecurrenceAutomatic(body map[string]interface{}) (string, error)
	PixDetailRecurrenceAutomatic(idRec string) (string, error)
	PixUpdateRecurrenceAutomatic(idRec string, body map[string]interface{}) (string, error)
	PixDetailRequestRecurrenceAutomatic(idSolicRec string) (string, error)
	PixUpdateRequestRecurrenceAutomatic(idSolicRec string, body map[string]interface{}) (string, error)
	PixDetailLocationRecurrenceAutomatic(id string) (string, error)
	PixListLocationRecurrenceAutomatic(inicio string, fim string) (string, error)
	PixUnlinkLocationRecurrenceAutomatic(id string) (string, error)
	PixCreateImmediateCharge(body map[string]interface{}) (string, error)
}
